name: image-processing-api

on:
  pull_request:
    paths:
      - 'extensions/image-processing-api/**'
      - '.github/workflows/image-processing-api.yaml'

  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  EXTENSION_PATH: 'extensions/image-processing-api'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@27082cecf3ff7a1742dbd5e12605f0cb59dce2d9 # v2-beta
        with:
          node-version: '14'
      - name: NPM Install
        run: npm install
      - name: Install Firebase CLI
