name: validate

on:
  pull_request:

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@27082cecf3ff7a1742dbd5e12605f0cb59dce2d9 # v2-beta
        with:
          node-version: '14'
      - name: NPM Install
        run: npm install
      # - name: Check Linting
      #   run: npm run check:linting
      - name: Check Formatting
        run: npm run check:formatting
      - name: Check TS Compiles
        run: npm run check:typescript
      - name: Check Spelling & Grammar
        run: npm run check:spelling
